# ETL - Transaction Dataset

In [1]:
import sqlite3
import pandas as pd

In [2]:
df = pd.read_csv("transaction_dataset.csv", index_col=0) # Lê o arquivo csv e inclui um DataFrame.

In [3]:
con = sqlite3.connect("projetorisco.db") # Conecta ao banco de dados SQLite.

In [4]:
cursor = con.cursor() # Armazena o cursor.

In [5]:
df.to_sql("transaction_dataset", con, if_exists="replace", index=False) # Salva o arquivo csv como tabela do Banco de 
                                                                        # Dados.

9841

In [6]:
pd.set_option('display.max_columns', None) # Estabelece que todas as colunas do DataFrame apareçam.

In [7]:
df_geral = pd.read_sql_query("""
    SELECT *
    FROM transaction_dataset
""", con) # Cria um novo DataFrame e armazena a consulta SQL. 

df_geral.head() # Apresenta o DataFrame.

,Index,Address,FLAG,Avg min between sent tnx,Avg min between received tnx,Time Diff between first and last (Mins),Sent tnx,Received Tnx,Number of Created Contracts,Unique Received From Addresses,Unique Sent To Addresses,min value received,max value received,avg val received,min val sent,max val sent,avg val sent,min value sent to contract,max val sent to contract,avg value sent to contract,total transactions (including tnx to create contract,total Ether sent,total ether received,total ether sent contracts,total ether balance,Total ERC20 tnxs,ERC20 total Ether received,ERC20 total ether sent,ERC20 total Ether sent contract,ERC20 uniq sent addr,ERC20 uniq rec addr,ERC20 uniq sent addr.1,ERC20 uniq rec contract addr,ERC20 avg time between sent tnx,ERC20 avg time between rec tnx,ERC20 avg time between rec 2 tnx,ERC20 avg time between contract tnx,ERC20 min val rec,ERC20 max val rec,ERC20 avg val rec,ERC20 min val sent,ERC20 max val sent,ERC20 avg val sent,ERC20 min val sent contract,ERC20 max val sent contract,ERC20 avg val sent contract,ERC20 uniq sent token name,ERC20 uniq rec token name,ERC20 most sent token type,ERC20_most_rec_token_type
0,1,0x00009277775ac7d0d59eaad8fee3d10ac6c805e8,0,844.26,1093.71,704785.63,721,89,0,40,118,0.000000,45.806785,6.589513,0.00,31.220000,1.200681,0.0,0.0,0.0,810,865.691093,586.466675,0.0,-279.224419,265.0,3.558854e+07,3.560317e+07,0.0,30.0,54.0,0.0,58.0,0.0,0.0,0.0,0.0,0.0,1.500000e+07,265586.147600,0.000000,1.683100e+07,271779.920000,0.0,0.0,0.0,39.0,57.0,Cofoundit,Numeraire
1,2,0x0002b44ddb1476db43c868bd494422ee4c136fed,0,12709.07,2958.44,1218216.73,94,8,0,5,14,0.000000,2.613269,0.385685,0.00,1.800000,0.032844,0.0,0.0,0.0,102,3.087297,3.085478,0.0,-0.001819,8.0,4.034283e+02,2.260809e+00,0.0,1.0,5.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,3.650000e+02,57.632615,2.260809,2.260809e+00,2.260809,0.0,0.0,0.0,1.0,7.0,Livepeer Token,Livepeer Token
2,3,0x0002bda54cb772d040f779e88eb453cac0daa244,0,246194.54,2434.02,516729.30,2,10,0,10,2,0.113119,1.165453,0.358906,0.05,3.538616,1.794308,0.0,0.0,0.0,12,3.588616,3.589057,0.0,0.000441,8.0,5.215121e+02,0.000000e+00,0.0,0.0,7.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,4.428198e+02,65.189009,0.000000,0.000000e+00,0.000000,0.0,0.0,0.0,0.0,8.0,None,XENON
3,4,0x00038e6ba2fd5c09aedb96697c8d7b8fa6632e5e,0,10219.60,15785.09,397555.90,25,9,0,7,13,0.000000,500.000000,99.488840,0.00,450.000000,70.001834,0.0,0.0,0.0,34,1750.045862,895.399559,0.0,-854.646303,14.0,1.711105e+04,1.141223e+04,0.0,2.0,11.0,0.0,11.0,0.0,0.0,0.0,0.0,0.0,1.141223e+04,1555.550174,100.000000,9.029231e+03,3804.076893,0.0,0.0,0.0,1.0,11.0,Raiden,XENON
4,5,0x00062d1dd1afb6fb02540ddad9cdebfe568e0d89,0,36.61,10707.77,382472.42,4598,20,1,7,19,0.000000,12.802411,2.671095,0.00,9.000000,0.022688,0.0,0.0,0.0,4619,104.318883,53.421897,0.0,-50.896986,42.0,1.628297e+05,1.235399e+05,0.0,4.0,23.0,0.0,27.0,0.0,0.0,0.0,0.0,0.0,9.000000e+04,4934.232147,0.000000,4.500000e+04,13726.659220,0.0,0.0,0.0,6.0,27.0,StatusNetwork,EOS

In [8]:
df_geral.info() # Traz o formato dos dados.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9841 entries, 0 to 9840
Data columns (total 50 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   Index                                                 9841 non-null   int64
 1   Address                                               9841 non-null   object
 2   FLAG                                                  9841 non-null   int64
 3   Avg min between sent tnx                              9841 non-null   float64
 4   Avg min between received tnx                          9841 non-null   float64
 5   Time Diff between first and last (Mins)               9841 non-null   float64
 6   Sent tnx                                              9841 non-null   int64
 7   Received Tnx                                          9841 non-null   int64
 8   Number of Created Contracts                           9841 non-null   int64
 9   Unique Received From Addresses                        9841 non-null   int64
 10  Unique Sent To Addresses                              9841 non-null   int64
 11  min value received                                    9841 non-null   float64
 12  max value received                                    9841 non-null   float64
 13  avg val received                                      9841 non-null   float64
 14  min val sent                                          9841 non-null   float64
 15  max val sent                                          9841 non-null   float64
 16  avg val sent                                          9841 non-null   float64
 17  min value sent to contract                            9841 non-null   float64
 18  max val sent to contract                              9841 non-null   float64
 19  avg value sent to contract                            9841 non-null   float64
 20  total transactions (including tnx to create contract  9841 non-null   int64
 21  total Ether sent                                      9841 non-null   float64
 22  total ether received                                  9841 non-null   float64
 23  total ether sent contracts                            9841 non-null   float64
 24  total ether balance                                   9841 non-null   float64
 25   Total ERC20 tnxs                                     9012 non-null   float64
 26   ERC20 total Ether received                           9012 non-null   float64
 27   ERC20 total ether sent                               9012 non-null   float64
 28   ERC20 total Ether sent contract                      9012 non-null   float64
 29   ERC20 uniq sent addr                                 9012 non-null   float64
 30   ERC20 uniq rec addr                                  9012 non-null   float64
 31   ERC20 uniq sent addr.1                               9012 non-null   float64
 32   ERC20 uniq rec contract addr                         9012 non-null   float64
 33   ERC20 avg time between sent tnx                      9012 non-null   float64
 34   ERC20 avg time between rec tnx                       9012 non-null   float64
 35   ERC20 avg time between rec 2 tnx                     9012 non-null   float64
 36   ERC20 avg time between contract tnx                  9012 non-null   float64
 37   ERC20 min val rec                                    9012 non-null   float64
 38   ERC20 max val rec                                    9012 non-null   float64
 39   ERC20 avg val rec                                    9012 non-null   float64
 40   ERC20 min val sent                                   9012 non-null   float64
 41   ERC20 max val sent                                   9012 non-null   float64
 42   ERC20 avg val sent                                   9012 non-null   float64
 43   ERC20 min val sent contract                          9012 non-null   float64
 44   ERC20 max val sent contract                          9012 non-null   float64
 45   ERC20 avg val sent contract                          9012 non-null   float64
 46   ERC20 uniq sent token name                           9012 non-null   float64
 47   ERC20 uniq rec token name                            9012 non-null   float64
 48   ERC20 most sent token type                           9000 non-null   object
 49   ERC20_most_rec_token_type                            8990 non-null   object
dtypes: float64(39), int64(8), object(3)
memory usage: 3.8+ MB

In [10]:
# Exclui a coluna 'Index'
df_geral = df_geral.drop(columns=['Index'])

In [9]:
# Converte a coluna 'FLAG' de int64 para object. Isso é feito para evitar que essas colunas sejam consideradas 
# nas estatísticas como valores numéricos.
df_geral['FLAG'] = df_geral['FLAG'].astype(object)

In [12]:
df_geral.to_sql("transaction_dataset", con, if_exists="replace", index=False) # Converte o DataFrame df_geral em uma 
                                                                              # tabela de mesmo nome do DataBase 
                                                                              # projetoecommerce.

9841

In [13]:
df_geral.info() # Traz o formato dos dados.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9841 entries, 0 to 9840
Data columns (total 49 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   Address                                               9841 non-null   object
 1   FLAG                                                  9841 non-null   object
 2   Avg min between sent tnx                              9841 non-null   float64
 3   Avg min between received tnx                          9841 non-null   float64
 4   Time Diff between first and last (Mins)               9841 non-null   float64
 5   Sent tnx                                              9841 non-null   int64
 6   Received Tnx                                          9841 non-null   int64
 7   Number of Created Contracts                           9841 non-null   int64
 8   Unique Received From Addresses                        9841 non-null   int64
 9   Unique Sent To Addresses                              9841 non-null   int64
 10  min value received                                    9841 non-null   float64
 11  max value received                                    9841 non-null   float64
 12  avg val received                                      9841 non-null   float64
 13  min val sent                                          9841 non-null   float64
 14  max val sent                                          9841 non-null   float64
 15  avg val sent                                          9841 non-null   float64
 16  min value sent to contract                            9841 non-null   float64
 17  max val sent to contract                              9841 non-null   float64
 18  avg value sent to contract                            9841 non-null   float64
 19  total transactions (including tnx to create contract  9841 non-null   int64
 20  total Ether sent                                      9841 non-null   float64
 21  total ether received                                  9841 non-null   float64
 22  total ether sent contracts                            9841 non-null   float64
 23  total ether balance                                   9841 non-null   float64
 24   Total ERC20 tnxs                                     9012 non-null   float64
 25   ERC20 total Ether received                           9012 non-null   float64
 26   ERC20 total ether sent                               9012 non-null   float64
 27   ERC20 total Ether sent contract                      9012 non-null   float64
 28   ERC20 uniq sent addr                                 9012 non-null   float64
 29   ERC20 uniq rec addr                                  9012 non-null   float64
 30   ERC20 uniq sent addr.1                               9012 non-null   float64
 31   ERC20 uniq rec contract addr                         9012 non-null   float64
 32   ERC20 avg time between sent tnx                      9012 non-null   float64
 33   ERC20 avg time between rec tnx                       9012 non-null   float64
 34   ERC20 avg time between rec 2 tnx                     9012 non-null   float64
 35   ERC20 avg time between contract tnx                  9012 non-null   float64
 36   ERC20 min val rec                                    9012 non-null   float64
 37   ERC20 max val rec                                    9012 non-null   float64
 38   ERC20 avg val rec                                    9012 non-null   float64
 39   ERC20 min val sent                                   9012 non-null   float64
 40   ERC20 max val sent                                   9012 non-null   float64
 41   ERC20 avg val sent                                   9012 non-null   float64
 42   ERC20 min val sent contract                          9012 non-null   float64
 43   ERC20 max val sent contract                          9012 non-null   float64
 44   ERC20 avg val sent contract                          9012 non-null   float64
 45   ERC20 uniq sent token name                           9012 non-null   float64
 46   ERC20 uniq rec token name                            9012 non-null   float64
 47   ERC20 most sent token type                           9000 non-null   object
 48   ERC20_most_rec_token_type                            8990 non-null   object
dtypes: float64(39), int64(6), object(4)
memory usage: 3.7+ MB

In [14]:
df_geral.columns = df_geral.columns.str.strip() # Remove espaços extras.

In [15]:
df_geral.columns = df_geral.columns.str.replace(' ', '_') # Substitui espaços por underline.

In [17]:
df_geral.to_sql("transaction_dataset", con, if_exists="replace", index=False) # Converte o DataFrame df_geral em uma 
                                                                              # tabela de mesmo nome do DataBase 
                                                                              # projetoecommerce.

9841

In [18]:
cursor.close() # Fecha o cursor.

con.close() # Fecha a conexão.